// Generated by https://quicktype.io

export interface TopLevel {
  playlist: Playlist
}

export interface Playlist {
  subscribers: Creator[]
  subscribed: boolean
  creator: Creator
  tracks: Track[]
  videoIds: null
  videos: null
  trackIds: TrackID[]
  updateFrequency: null
  backgroundCoverId: number
  backgroundCoverUrl: null
  titleImage: number
  titleImageUrl: null
  englishTitle: null
  opRecommend: boolean
  subscribedCount: number
  cloudTrackCount: number
  userId: number
  trackNumberUpdateTime: number
  trackUpdateTime: number
  createTime: number
  highQuality: boolean
  coverImgId: number
  newImported: boolean
  updateTime: number
  specialType: number
  coverImgUrl: string
  trackCount: number
  commentThreadId: string
  privacy: number
  playCount: number
  adType: number
  tags: string[]
  ordered: boolean
  description: string
  status: number
  name: string
  id: number
  shareCount: number
  commentCount: number
}

export interface Creator {
  defaultAvatar: boolean
  province: number
  authStatus: number
  followed: boolean
  avatarUrl: string
  accountStatus: number
  gender: number
  city: number
  birthday: number
  userId: number
  userType: number
  nickname: string
  signature: string
  description: string
  detailDescription: string
  avatarImgId: number
  backgroundImgId: number
  backgroundUrl: string
  authority: number
  mutual: boolean
  expertTags: null
  experts: null
  djStatus: number
  vipType: number
  remarkName: null
  avatarImgIdStr: string
  backgroundImgIdStr: string
  avatarImgId_str: string
}

export interface TrackID {
  id: number
  v: number
  at: number
  alg: null
}

export interface Track {
  name: string
  id: number
  pst: number
  t: number
  ar: Ar[]
  alia: string[]
  pop: number
  st: number
  rt: null | string
  fee: number
  v: number
  crbt: null
  cf: string
  al: Al
  dt: number
  h: L | null
  m: L | null
  l: L
  a: null
  cd: string
  no: number
  rtUrl: null
  ftype: number
  rtUrls: any[]
  djId: number
  copyright: number
  s_id: number
  mark: number
  originCoverType: number
  noCopyrightRcmd: NoCopyrightRcmd | null
  rtype: number
  rurl: null
  mst: number
  cp: number
  mv: number
  publishTime: number
}

export interface Al {
  id: number
  name: string
  picUrl: string
  tns: any[]
  pic: number
  pic_str?: string
}

export interface Ar {
  id: number
  name: string
  tns: any[]
  alias: any[]
}

export interface L {
  br: number
  fid: number
  size: number
  vd: number
}

export interface NoCopyrightRcmd {
  type: number
  typeDesc: string
  songId: null
}
