// Generated by https://quicktype.io
// http://localhost:3000/song/url?id=405998841,33894312

export interface SongPlayUrlInfo {
  id: number
  url: string
  br: number
  size: number
  md5: string
  code: number
  expi: number
  type: string
  gain: number
  fee: number
  uf: null
  payed: number
  flag: number
  canExtend: boolean
  freeTrialInfo: null
  level: string
  encodeType: string
}
